#!/bin/bash

# Slackware build script for gnome-shell-extension-show-desktop

# Copyright 2022 Nathaniel Russell <naterussell83@gmail.com>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=gnome-shell-extension-show-desktop
SRCNAM=Show-Desktop-Button
VERSION=${VERSION:-30}
BUILD=${BUILD:-1}
TAG=${TAG:-_gfs}
PKGTYPE=${PKGTYPE:-txz}
uuid=show-desktop-button@amivaleo
_commit=43d4c9d4855903aa727bfeab091b0c3e8f3b4940

TMP=${TMP:-/tmp/gfs}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

ARCH=noarch

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $SRCNAM
git clone https://github.com/amivaleo/Show-Desktop-Button.git
cd $SRCNAM
git checkout $_commit

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
DOCS="README.md"
mv $DOCS $PKG/usr/doc/$PRGNAM-$VERSION


UUID=$PKG/usr/share/gnome-shell/extensions/$uuid
mkdir -p $UUID
cp -r * $UUID/
mkdir -p $PKG/usr/share/glib-2.0
cp -r schemas $PKG/usr/share/glib-2.0
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc
zcat $CWD/doinst.sh.gz > $PKG/install/doinst.sh

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
